import { NgModule } from '@angular/core';

import {
  MatSidenavModule,
  MatToolbarModule,
  MatButtonModule,
  MatButtonToggleModule,
  MatTableModule,
  MatChipsModule,
  MatInputModule,
  MatSelectModule,
  MatIconModule,
  MatListModule,
  MatPaginatorModule,
  MatSortModule,
  MatDatepickerModule,
  MatSnackBarModule,
  MatCardModule,
  MatDialogModule,
  MatGridListModule,
  MatCheckboxModule,
  MatStepperModule,
  MatSliderModule,
  MatMenuModule,
  MatTooltipModule,
  MatRadioModule
} from '@angular/material';

@NgModule({
  imports: [
    MatTooltipModule,
    MatGridListModule,
    MatCardModule,
    MatDialogModule,
    MatButtonModule,
    MatButtonToggleModule,
    MatSidenavModule,
    MatToolbarModule,
    MatTableModule,
    MatChipsModule,
    MatInputModule,
    MatSelectModule,
    MatIconModule,
    MatListModule,
    MatCheckboxModule,
    MatMenuModule,
    MatPaginatorModule,
    MatSortModule,
    MatDatepickerModule,
    MatSnackBarModule,
    MatSliderModule,
    MatStepperModule,
    MatRadioModule
  ],
  declarations: [],
  exports: [
    MatTooltipModule,
    MatGridListModule,
    MatCardModule,
    MatDialogModule,
    MatButtonModule,
    MatButtonToggleModule,
    MatSidenavModule,
    MatToolbarModule,
    MatCheckboxModule,
    MatMenuModule,
    MatTableModule,
    MatChipsModule,
    MatInputModule,
    MatSelectModule,
    MatIconModule,
    MatListModule,
    MatPaginatorModule,
    MatSortModule,
    MatDatepickerModule,
    MatSnackBarModule,
    MatSliderModule,
    MatStepperModule,
    MatRadioModule
  ]
})
export class MaterialModule { }
